services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  grpc:
    container_name: grpc

    depends_on:
      - db
    links:
      - db

    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50051:50051'

volumes:
  postgres_data:
