# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rng.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'rng.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trng.proto\"\x15\n\x13RandomNumberRequest\"#\n\x11RandomNumberReply\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32Y\n\x13RandomNumberService\x12\x42\n\x14generateRandomNumber\x12\x14.RandomNumberRequest\x1a\x12.RandomNumberReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rng_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANDOMNUMBERREQUEST']._serialized_start=13
  _globals['_RANDOMNUMBERREQUEST']._serialized_end=34
  _globals['_RANDOMNUMBERREPLY']._serialized_start=36
  _globals['_RANDOMNUMBERREPLY']._serialized_end=71
  _globals['_RANDOMNUMBERSERVICE']._serialized_start=73
  _globals['_RANDOMNUMBERSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
